import { authorizeSchoolActor } from '../../_lib/auth.js';
import { failure, json } from '../../_lib/http.js';
const ADMIN = new Set(['school_admin']);
export async function auditHistory(context) {
  try { const schoolId=String(context.params.schoolId); await authorizeSchoolActor(context,schoolId,ADMIN); const result=await context.env.DB.prepare('SELECT id,actor_brasa_id AS actorId,action,resource_type AS resourceType,resource_id AS resourceId,snapshot_json AS snapshotJson,occurred_at AS occurredAt FROM school_audit_log WHERE school_id=? ORDER BY occurred_at DESC LIMIT 250').bind(schoolId).all(); return json({data:result.results.map(row=>({...row,snapshot:JSON.parse(row.snapshotJson),snapshotJson:undefined}))}); } catch(error){return failure(error);}
}
export async function schoolExport(context) {
  try { const schoolId=String(context.params.schoolId); await authorizeSchoolActor(context,schoolId,ADMIN); const [school,memberships,lessons,audit]=await Promise.all([context.env.DB.prepare('SELECT id,slug,name,country_code AS countryCode,default_locale AS defaultLocale,status,public_profile AS publicProfile,supported_locales_json AS supportedLocalesJson,brand_primary_color AS brandPrimaryColor,support_url AS supportUrl,created_at AS createdAt,updated_at AS updatedAt FROM school_tenants WHERE id=?').bind(schoolId).first(),context.env.DB.prepare('SELECT actor_brasa_id AS actorId,role,status,created_at AS createdAt,updated_at AS updatedAt FROM school_memberships WHERE school_id=? ORDER BY created_at').bind(schoolId).all(),context.env.DB.prepare('SELECT id,slug,locale,title,summary,body_json AS bodyJson,accessibility_json AS accessibilityJson,offline_eligible AS offlineEligible,status,published_at AS publishedAt,created_at AS createdAt,updated_at AS updatedAt FROM school_lessons WHERE school_id=? ORDER BY created_at').bind(schoolId).all(),context.env.DB.prepare('SELECT actor_brasa_id AS actorId,action,resource_type AS resourceType,resource_id AS resourceId,snapshot_json AS snapshotJson,occurred_at AS occurredAt FROM school_audit_log WHERE school_id=? ORDER BY occurred_at LIMIT 5000').bind(schoolId).all()]); const payload={schema:'brasa.school-export.v1',exportedAt:new Date().toISOString(),school:{...school,publicProfile:Boolean(school.publicProfile),supportedLocales:JSON.parse(school.supportedLocalesJson),supportedLocalesJson:undefined},memberships:memberships.results,lessons:lessons.results.map(row=>({...row,body:JSON.parse(row.bodyJson),accessibility:JSON.parse(row.accessibilityJson),offlineEligible:Boolean(row.offlineEligible),bodyJson:undefined,accessibilityJson:undefined})),audit:audit.results.map(row=>({...row,snapshot:JSON.parse(row.snapshotJson),snapshotJson:undefined}))}; return new Response(JSON.stringify(payload),{headers:{'content-type':'application/json; charset=utf-8','content-disposition':`attachment; filename="${schoolId}-brasa-export.json"`,'cache-control':'no-store'}}); } catch(error){return failure(error);}
}
